name: rusted
description: Rusted brings the Result class from Rust along with other utilities.
version: 1.0.1
repository: https://github.com/aarol/rusted
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
